services:
  # Servidor Web con PHP 8.2 y Apache
  web:
    build: .  # Esto le dice a Docker que use el Dockerfile de esta carpeta
    ports:
      - "8000:80"
    environment:
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ADMIN_NAME: "${ADMIN_NAME}"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db

  # Base de Datos MySQL 8.0
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beatdrop_db
      MYSQL_USER: beatdrop_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  # Herramienta phpMyAdmin para gestionar la BBDD desde el navegador
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Europe/Madrid"
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "admin"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
    volumes:
      - ./n8n:/home/node/.n8n

volumes:
  db_data:
